# https://prettier.io/docs/en/options.html

endOfLine: "lf"

printWidth: 100
tabWidth: 4
useTabs: false

semi: true
singleQuote: true

trailingComma: "es5"
bracketSpacing: true
arrowParens: "always"

jsxSingleQuote: false
jsxBracketSameLine: false
