# https://prettier.io/docs/en/options.html

endOfLine: 'auto'

printWidth: 120
tabWidth: 4
useTabs: false

semi: true
singleQuote: true

trailingComma: 'es5'
bracketSpacing: true
arrowParens: 'always'

jsxSingleQuote: false
jsxBracketSameLine: false

overrides:
  - files:
      - '*.yml'
      - '*.yaml'
    options:
      tabWidth: 2
