version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo === Install Phase ===
      - pwd
      - yum install -y zip
      - npm install -g yarn
  pre_build:
    commands:
      - echo === Pre-build Phase ===
      - yarn install
  build:
    commands:
      - echo === Build Phase ===
      - yarn build
  post_build:
    commands:
      - echo === Post-build Phase ===
      - cd build/
      - zip -9 build.zip *

artifacts:
  files:
    build/*
  name: apexstats-artifact
  discard-paths: yes

cache:
  paths:
    - 'node_modules/'